service: aws-srvrless-lf-game-voting

provider:
  name: aws
  architecture: x86_64
  
functions:
  aws-srvrless-lf-game-voting: 
    handler: dist/index.handler
    name: aws-srvrless-lf-game-voting
    description: AWS serverless lambda function